authors/urls.py
from django.urls import include, path

from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('register/create/', views.register_create, name="register_create"),
    path('login/', views.login_view, name="login"),
    path('login/create/', views.login_create, name="login_create"),
    path('logout/', views.logout_view, name="logout"),
]

project/urls.py
from turtle import st
from xml.dom.minidom import Document

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
]

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/search/', views.search, name="search"),
    path('recipes/category/<int:category_id>/',
         views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

recipes/models.py
from distutils.command.upload import upload
from turtle import title

from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=164)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=64)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=64)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, default=None)

    def __str__(self):
        return self.title

recipes/views.py

import os

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render
from utils.pagination import make_pagination

from .models import Recipe

PER_PAGE = int(os.environ.get('PER_PAGE', 6))


def home(request):

    recipes = Recipe.objects.filter(is_published=True).order_by('-id')
    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/home.html', {'recipes': page_obj,
                                                 'pagination_range': pagination_range,
                                                 })


def category(request, category_id):

    recipes = get_list_or_404(
        Recipe.objects.filter(category__id=category_id, is_published=True).order_by('-id'))

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)
    return render(request, 'recipes/category.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'title': f'{recipes[0].category.name}',
    })


def recipe(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)

    return render(request, 'recipes/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True})


def search(request):
    search_term = request.GET.get('q', '').strip()
    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term)
        ),
        is_published=True).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/search.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'q={search_term}&',
        'title': f'Search: {search_term}',
        'search_term': search_term,
    })

recipes/templates/recipes/partials/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/fontawesome.min.css"
        integrity="sha512-KVdV5HNnN1f6YOANbRuNxyCnqyPICKUmQusEkyeRg4X0p8K1xCdbHs32aA7pWo6WqMZk0wAzl29cItZh8oBPYQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/solid.min.css"
        integrity="sha512-LUxUs00S05YspUb2HCuUTBqTqbjJm2uNvwRXVTcl/jkr9ygYZptXhfknc52iBnPUNgHHHC9ivU4RV6UFxLxhfg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link href="{% static 'recipes/css/styles.css' %}" rel="stylesheet">

recipes/templates/recipes/partials/recipe.html

        <div class="recipe recipe-item">
            {% if recipe.cover %}
                <div class="recipe-cover">
                    <a href="{% url 'recipes:recipe' recipe.id %}">
                        <img src="{{recipe.cover.url}}" alt="{{ recipe.title}}">
                    </a>
                </div>
            {% endif %}
            <div class="recipe-title-container">
                    <h2 class="recipe-title">
                        <a href="{% url 'recipes:recipe' recipe.id %}">
                            {{recipe.title}}
                        </a>
                    </h2>
                </a>
            </div>
            <div class="recipe-author">
                {% if recipe.author is not None%}
                <span class="recipe-author-item">
                    <i class="fa-solid fa-user"></i>
                        {% if not recipe.author.first_name %}
                            {{recipe.author}}
                        {% else %}
                            {{recipe.author.first_name}} {{recipe.author.last_name}}
                        {% endif %}
                </span>
                {% endif %}
                <span class="recipe-author-item">
                    <i class="fa-solid fa-calendar-alt"></i>
                    {{ recipe.created_at|date:"d/m/Y" }}
                </span>
                {% if recipe.category is not None %}
                    <span class="recipe-author-item">
                        <a href="{% url 'recipes:category' recipe.category.id %}">
                            <i class="fa-solid fa-layer-group"></i>
                            {{recipe.category.name}}
                        </a>
                    </span>
                {% endif %}
            </div>

            <div class="recipe-content">
                <p>{{recipe.description}}</p>
            </div>

            <div class="recipe-meta-container">
                <div class="recipe-meta recipe-preparation">
                    <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
                    <div class="recipe-meta-text">
                        {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
                    </div>
                </div>
                <div class="recipe-meta recipe-servings">
                    <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
                    <div class="recipe-meta-text">
                        {{ recipe.servings }} {{ recipe.servings_unit }}
                    </div>
                </div>
            </div>

            {% if is_detail_page is not True %}
            <footer class="recipe-footer">
                <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                    <i class="fas fa-eye"></i>
                    <span>ver mais...</span>
                </a>
            </footer>
            {% endif %}


            {% if is_detail_page is True %}
            <div class="recipe-content preparation-steps">
                {% if recipe.preparation_steps_is_html is True %}
                    <p>{{recipe.preparation_steps|safe}}</p>
                {% else %}
                    <p>{{recipe.preparation_steps|linebreaksbr}}</p>
                {% endif %}
            </div>
            {% endif %}
        
        </div>
        